package cn.sjj.ktv.store;

import java.util.ArrayList;
import java.util.List;

import cn.sjj.ktv.bean.Song;

/**
 * @auther 宋疆疆
 * @since 2017/6/16.
 */
public class Japanese {

    public static List<Song> songs;

    static {
        songs = new ArrayList<>();
        songs.add(new Song("", "", ""));
        songs.add(new Song("プレイス・オブ・ピリオド", "諫山実生", "寒蝉鸣泣之时"));
        songs.add(new Song("Letter Song", "初音ミク", "doriko", "致十年后的我"));
        songs.add(new Song("Love is...", "加藤ミリヤ", "奔向地球ED"));
        songs.add(new Song("想い出がいっぱい", "下川みくに", ""));
        songs.add(new Song("かけがえのない詩", "mihimaru GT", "大和美姬丸", "2007 ドラえもん のび太の新魔界大冒険 ~7人の魔法使い~"));
        songs.add(new Song("ReReハロ〜終われそうにない夏〜", "7!!", ""));
        songs.add(new Song("I will", "Chelsy", "青春之旅"));
        songs.add(new Song("一番の宝物", "LiSA", "Angel Beats!"));
        songs.add(new Song("Beautiful World", "宇多田光", "福音战士新剧场版：序"));
        songs.add(new Song("いつも何度でも", "伊藤サチコ", "千と千尋の神隠し", "木村弓"));
        songs.add(new Song("夜の国", "Annabel", "黑街ED"));
        songs.add(new Song("世界は恋に落ちている", "CHiCO with HoneyWorks", "青春之旅OP"));
        songs.add(new Song("運命のルーレット廻して", "ZARD", "柯南OP", "转动命运之轮", "ザード"));
        songs.add(new Song("蜜蜜蜜", "あゆみくりかまき", "Punch Line"));
        songs.add(new Song("Questions", "中村優", "迷宫塔"));
        songs.add(new Song("キミボク", "ムラマサ☆", ""));
        songs.add(new Song("SWINGING", "ムラマサ☆", "迷宫塔"));
        songs.add(new Song("Season", "瀧川ありさ", "七大罪"));
        songs.add(new Song("オルフェンズの涙", "MISIA", "高达 铁血的奥尔芬斯"));
        songs.add(new Song("Knew day", "(K)NoW＿NAME", "灰与幻想的格林姆迦尔"));
        songs.add(new Song("GIRAFFE BLUES ~Mikumo Solo~", "美雲ΔJUNNA", "超时空要塞Δ"));
        songs.add(new Song("GIRAFFE BLUES ~Freyja Solo~", "フレイアΔ鈴木みのり", "超时空要塞Δ"));
        songs.add(new Song("風は予告なく吹く", "ワルキューレ", "超时空要塞Δ"));
        songs.add(new Song("破滅の純情", "ワルキューレ", "超时空要塞Δ"));
        songs.add(new Song("絶対零度θノヴァティック", "ワルキューレ", "超时空要塞Δ"));
        songs.add(new Song("いろがみ", "能登麻美子", "地狱少女"));
        songs.add(new Song("ノイズ", "ミオヤマザキ", "地狱少女"));
        songs.add(new Song("ふたりの珊瑚礁", "高垣彩阳", "地狱少女 三鼎"));
        songs.add(new Song("いちぬけ", "能登麻美子", "地狱少女 三鼎"));
        songs.add(new Song("月华-tsukihana-", "北出菜奈", "地狱少女 三鼎"));
        songs.add(new Song("あいぞめ", "能登麻美子", "地狱少女 二笼"));
        songs.add(new Song("NightmaRe", "SNoW", "地狱少女 二笼"));
        songs.add(new Song("かりぬい", "能登麻美子", "地狱少女"));
        songs.add(new Song("逆さまの蝶", "SNoW", "地狱少女"));
        songs.add(new Song("WOKE FROM DREAMING", "the delgados", "GUNSLINGER GIRL"));
        songs.add(new Song("THE LIGHT BEFORE WE LAND", "the delgados", "GUNSLINGER GIRL"));
        songs.add(new Song("DOPO IL SOGNO ～梦のあとに～", "うえのけいこ", "GUNSLINGER GIRL"));
        songs.add(new Song("human", "Lia", "GUNSLINGER GIRL -IL TEATRINO-"));
        songs.add(new Song("たった1つの想い", "KOKIA 吉田亚纪子", "GUNSLINGER GIRL -IL TEATRINO-"));
        songs.add(new Song("スカボロー．フェア", "多田葵", "GUNSLINGER GIRL -IL TEATRINO-"));
        songs.add(new Song("doll", "多田葵", "GUNSLINGER GIRL -IL TEATRINO-"));
        songs.add(new Song("灼け落ちない翼", "多田葵", "Charlotte"));
        songs.add(new Song("ツギハギスタッカート", "MIKU", "拼凑的断音", "hanser"));
        songs.add(new Song("鳥の詩", "Lia", "鸟之诗"));
        songs.add(new Song("青空", "Lia", "AIR"));
        songs.add(new Song("明日への扉", "I WiSH", ""));
        songs.add(new Song("プラスチックスマイル", "Honey Bee", "七彩的素描"));
        songs.add(new Song("梦の中へ", "榎本温子 鈴木千尋", "他和她的事情"));
        songs.add(new Song("Shadow and Truth", "ONE III NOTES", "ACCA13区监察课"));
        songs.add(new Song("STYX HELIX", "MYTH & ROID", "Re:从零开始异世界生活"));
        songs.add(new Song("Good bye, yesterday", "渡辺みづき", "罗密欧与朱丽叶"));
        songs.add(new Song("东京夏日相会 - 无念白", "yukiri", "Hanser"));
        songs.add(new Song("奈落の花", "島みやえい子", "寒蝉鸣泣之时解", "岛宫荣子"));
        songs.add(new Song("未来へ", "玉城千春", "Kiroro"));
        songs.add(new Song("はじまりのしるし", "Chima", "从零开始的魔法书"));
        songs.add(new Song("つま先立ち", "Chima", ""));
        songs.add(new Song("DEAREST DROP", "田所あずさ", "末日时在做什么？有没有空？可以来拯救吗？"));
        songs.add(new Song("フロム", "TRUE", "末日时在做什么？有没有空？可以来拯救吗？"));
        songs.add(new Song("なんでもないや", "RADWIMPS", "你的名字"));
        songs.add(new Song("夢灯籠", "RADWIMPS", "你的名字"));
        songs.add(new Song("前前前世", "RADWIMPS", "你的名字"));
        songs.add(new Song("月花", "Nano.Ripe", ""));
        songs.add(new Song("面影ワープ", "Nano.Ripe", "面影萦绕"));
        songs.add(new Song("ハイリープ", "Nano.Ripe", ""));
        songs.add(new Song("アンサーソング", "Nano.Ripe", ""));
        songs.add(new Song("月影とブランコ", "Nano.Ripe", "月影和秋千"));
        songs.add(new Song("なないろびより", "Nano.Ripe", "七彩日和"));
        songs.add(new Song("影踏み", "Nano.Ripe", "踩影子"));
        songs.add(new Song("ハナノイロ", "Nano.Ripe", "花之色彩"));
        songs.add(new Song("パトリシア", "Nano.Ripe", "Patricia"));
        songs.add(new Song("ルーペ", "Nano.Ripe", ""));
        songs.add(new Song("4分間", "Nano.Ripe", ""));
        songs.add(new Song("神様", "Nano.Ripe", ""));
        songs.add(new Song("もしもの話", "Nano.Ripe", ""));
        songs.add(new Song("水性キャスト", "Nano.Ripe", "水性角色"));
        songs.add(new Song("アドバルーン", "Nano.Ripe", "广告气球"));
        songs.add(new Song("スターチャート", "Nano.Ripe", "星图"));
        songs.add(new Song("マイガール", "Nano.Ripe", "my girl"));
        songs.add(new Song("パルスター", "Nano.Ripe", "死亡之星"));
        songs.add(new Song("リップシンク", "Nano.Ripe", "假唱"));
        songs.add(new Song("帰り道", "Nano.Ripe", "归途"));
        songs.add(new Song("夢路", "Nano.Ripe", ""));
        songs.add(new Song("架空線", "Nano.Ripe", ""));
        songs.add(new Song("スノードロップ ", "Nano.Ripe", "雪花莲"));
        songs.add(new Song("花残り月", "Nano.Ripe", "落花之月"));
        songs.add(new Song("细胞キオク", "Nano.Ripe", "细胞记忆）"));
        songs.add(new Song("ゆきのせい", "Nano.Ripe", "雪之声"));
        songs.add(new Song("ブルーバード", "いきものがかり", "青鸟"));
        songs.add(new Song("ペガサス幻想", "MAKE-UP", "圣斗士星矢"));
        songs.add(new Song("駅", "Tiara", ""));
        songs.add(new Song("Secret Baseー君がくれたものー(10 Years After Ver.) ", "ZONE", "未闻花名"));
        songs.add(new Song("butter fly", "和田光司", "数码宝贝"));
        songs.add(new Song("夢をかなえてドラえもん", "", "哆啦A梦"));
        songs.add(new Song("RTB", "ムッシュかまやつ", "战斗妖精雪风", "Hajime Ueshiba"));
        songs.add(new Song("世界が终るまでは", "WANDS", "灌篮高手"));
        songs.add(new Song("君が好きだと叫びたい", "baad", "灌篮高手"));
        songs.add(new Song("Re:Re:", "ASIAN KUNG-FU GENERATION", ""));
        songs.add(new Song("さくら～あなたに出会えてよかった～", "rsp", "高野建一"));
        songs.add(new Song("樱花樱花想见你", "高野建一", ""));
        songs.add(new Song("空も飞べるはず", "spitz", ""));
        songs.add(new Song("Your song", "Yun*chi", "记录的地平线"));
        songs.add(new Song("終わらないメロディーを歌いだしました", "小松未可子", "神不在的星期天"));
        songs.add(new Song("TOMORROW", "岡本真夜", ""));
        songs.add(new Song("ラピスラズリ", "藍井エイル", "阿尔斯兰战记"));
        songs.add(new Song("くちづけDiamond", "WEAVER", "山田君与7个魔女"));
        songs.add(new Song("ロンリー・チャップリン", "鈴木聖美", "ラッツ&スター"));
        songs.add(new Song("Thank you for everything", "岩田さゆり", "岩田小百合"));
        songs.add(new Song("あつい気持ち", "ONE STEP COMMUNICATE", "ワンステップ・コミュニケート"));
        songs.add(new Song("Lil' Goldfish", "まりか", ""));
        songs.add(new Song("long kiss good bye", "halcali", "火影忍者ed22"));
        songs.add(new Song("蜉蝣 ", "下級生2 ~瞳の中の少女たち", "かげろう"));
        songs.add(new Song("风になる", "辻亜弥乃", "幻化成风"));
        songs.add(new Song("夏祭り", "JITTERIN'JINN", "Whiteberry"));
        songs.add(new Song("ナミダ", "2BACKKA", ""));
        songs.add(new Song("爱·おぼえていますか", "林明美", "超时空要塞", "饭岛真理"));
        songs.add(new Song("夢の中へ", "井上陽水", "斉藤由貴"));
        songs.add(new Song("手纸~拝啓 十五の君へ", "アンジェラ・アキ", ""));
        songs.add(new Song("いつも何度でも", "", "千与千寻"));
        songs.add(new Song("いつかの自分", "anderlust", "野球少年op"));
        songs.add(new Song("明日、春が来たら", "anderlust", "野球少年ed"));
        songs.add(new Song("若者のすべて", "anderlust", "野球少年ed2"));
        songs.add(new Song("Swallowtail Butterfly ~あいのうた~", "anderlust", ""));
        songs.add(new Song("Wishing", "西野カナ", ""));
        songs.add(new Song("if", "西野カナ", ""));
        songs.add(new Song("PIECES OF A DREAM", "CHEMISTRY", "ReLIFE 重返17岁"));
        songs.add(new Song("merry-go-round", "CHEMISTRY", "高达UC"));
        songs.add(new Song("さっちゃんのセクシーカレー", "大森靖子", "食戟之灵"));
        songs.add(new Song("マジックミラー", "大森靖子", "食戟之灵"));
        songs.add(new Song("希望の唄", "ウルトラタワー", "食戟之灵"));
        songs.add(new Song("ハロー", "ウルトラタワー", ""));
        songs.add(new Song("スパイス", "東京カランコロン", "食戟之灵"));
        songs.add(new Song("お料理行進曲", "東京カランコロン", "食戟之灵"));
        songs.add(new Song("島呗", "宫泽和史", "岛呗"));
        songs.add(new Song("タッチ", "岩崎良美", "Touch"));
        songs.add(new Song("風のメッセージ", "芹澤廣明 ", "Touch"));
        songs.add(new Song("Let Me Be With You", "ROUND TABLE featuring Nino", "人形电脑天使心"));
        songs.add(new Song("夏待ち", "ROUND TABLE featuring Nino", "水星领航员ED"));
        songs.add(new Song("Rainbow", "ROUND TABLE featuring Nino", "水星领航员ED"));
        songs.add(new Song("パズル", "ROUND TABLE featuring Nino", ""));
        songs.add(new Song("TRAIN-TRAIN", "The Blue Hearts", "旋转少女"));
        songs.add(new Song("脳天気", "The Blue Hearts", "旋转少女"));
        songs.add(new Song("夕暮れ", "The Blue Hearts", "旋转少女"));
        songs.add(new Song("英雄にあこがれて", "The Blue Hearts", "旋转少女"));
        songs.add(new Song("終わらない歌", "The Blue Hearts", "旋转少女"));
        songs.add(new Song("人にやさしく", "The Blue Hearts", "旋转少女"));
        songs.add(new Song("月の爆撃機", "The Blue Hearts", "旋转少女"));
        songs.add(new Song("1000のバイオリン", "The Blue Hearts", "旋转少女"));
        songs.add(new Song("なまえのないうた", "镜音", ""));
        songs.add(new Song("罠", "THE BACK HORN", "高达00"));
        songs.add(new Song("DAYBREAK'S BELL", "L'Arc～en～Ciel", "高达00"));
        songs.add(new Song("Ash Like Snow", "the brilliant green", "高达00", "灰哀之雪"));
        songs.add(new Song("フレンズ", "stephanie", "高达00"));
        songs.add(new Song("儚くも永久のカナシ", "UVERworld", "高达00"));
        songs.add(new Song("Prototype", "石川智晶", "高达00"));
        songs.add(new Song("泪のムコウ", "ステレオボニー", "高达00"));
        songs.add(new Song("trust you", "伊藤由奈", "高达00"));
        songs.add(new Song("Unlimited Sky", "Tommy heavenly6", "高达00"));
        songs.add(new Song("もどかしい世界の上で", "牧野由依", "欢迎来到NHK"));
        songs.add(new Song("夢をかなえてドラえもん", "春奈るな", ""));
        songs.add(new Song("君色シグナル", "春奈るな", "路人女主的养成方法"));
        songs.add(new Song("カラフル", "迟井美空", "路人女主的养成方法"));
        songs.add(new Song("サヨナラの手前", "迟井美空", ""));
        songs.add(new Song("", "迟井美空", ""));
        songs.add(new Song("ナミダアメ", "azusa", ""));
        songs.add(new Song("遥かなる梦に", "beyond", ""));
        songs.add(new Song("待つわ", "あみん", "日本经典老歌"));
        songs.add(new Song("ルビーの指環", "寺尾聰", "日本经典老歌"));
        songs.add(new Song("3年目の浮気", "ヒロシ＆キーボー", "日本经典老歌"));
        songs.add(new Song("岬めぐり", "山本コウタロー", "日本经典老歌"));
        songs.add(new Song("ひと夏の経験", " 山口百恵", "日本经典老歌"));
        songs.add(new Song("恋人も濡れる街角", "中村雅俊", "日本经典老歌"));
        songs.add(new Song("星空のディスタンス", "THE ALFEE", "日本经典老歌"));
        songs.add(new Song("A面で恋をして", "ナイアガラ・トライアングル", "日本经典老歌"));
        songs.add(new Song("恋人", "徳永英明", "日本经典老歌"));
    }
}
